### ISSUE TITLE
Not running for me + feature request

### ISSUE THREAD

**Issue by Kristofferyx** [cmz97/Multi-Thread-500px-Scraper#1]
When i run the command: X:\500px>python39 500pxScraperParallelProcess.py <nameofthephotographer> i get this error:

[INFO] Found 0 Pre-existing Images
Traceback (most recent call last):
  File "X:\500px\500pxScraperParallelProcess.py", line 231, in <module>
    urlListFromProfilePage = getUrlListFromProfilePage(mydriver)
  File "X:\500px\500pxScraperParallelProcess.py", line 100, in getUrlListFromProfilePage
    imgPortfolio = WebDriverWait(driver, args.PORTFOLIO_PAGE_LOAD_TIMEOUT).until(EC.visibility_of_element_located((By.XPATH, "/html/body/div[4]/div[3]/div/div"))) # get element contain pictures from portfolio
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

I've checked that geckodriver is in PATH, i've installed all prerequisites and didn't get an error.. I run python a windows 10 machine, i also use several python instances, thats why it says python39. What could i be doing wrong? If i remove --headless i see that it goes to the right page but then the script stops working after that. Nothing gets downloaded.. The log from geckodriver is: 

1613489281711	geckodriver	INFO	Listening on 127.0.0.1:49637
1613489284728	mozrunner::runner	INFO	Running command: "C:\\Program Files\\Mozilla Firefox\\firefox.exe" "--marionette" "--headless" "-foreground" "-no-remote" "-profile" "C:\\Users\\Admin\\AppData\\Local\\Temp\\rust_mozprofileZy9hEd"
*** You are running in headless mode.
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new Error("", "(unknown module)"))
1613489288213	Marionette	INFO	Listening on port 49827
console.warn: SearchSettings: "get: No settings file exists, new profile?" (new Error("", "(unknown module)"))
1613489288592	Marionette	WARN	TLS certificate errors will be ignored for this session
1613489288646	Marionette	ERROR	[15] No reply from Marionette:Register

Also, i wonder if you can add a timer for when it rechecks the photographers site, like every 2 hour it checks  if more pics added, and if there is it download it. Or that if no pictures has been added it will not download the same pic again, so some sort of simple database is needed. Would be awesome!

**Comment by cmz97** [comment]
Hi Kristoffer,

Thanks for reaching out. I saw your email, I am just gonna reply here. 

Can you provide the argument that you run this program with? like the user name and all the stuff.  And yeah, a timer should be a pretty simple feature.

Like this `  python3 ./500pxScraperParallelProcess 'kordan'`

Let me take a look after you provide me with the argument.

Thanks!

**Comment by Kristofferyx** [comment]
X:\500px>python39 ./500pxScraperParallelProcess.py kvack
[INFO] Found 0 Pre-existing Images
Traceback (most recent call last):
  File "X:\500px\500pxScraperParallelProcess.py", line 231, in <module>
    urlListFromProfilePage = getUrlListFromProfilePage(mydriver)
  File "X:\500px\500pxScraperParallelProcess.py", line 100, in getUrlListFromProfilePage
    imgPortfolio = WebDriverWait(driver, args.PORTFOLIO_PAGE_LOAD_TIMEOUT).until(EC.visibility_of_element_located((By.XPATH, "/html/body/div[4]/div[3]/div/div"))) # get element contain pictures from portfolio
  File "C:\Users\Admin\AppData\Local\Programs\Python\Python39\lib\site-packages\selenium\webdriver\support\wait.py", line 80, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:

kvack is https://500px.com/p/kvack, 

and i use: python39 ./500pxScraperParallelProcess.py kvack

**Comment by cmz97** [comment]
Thanks! I will get on it after work.

**Comment by Kristofferyx** [comment]
> Thanks! I will get on it after work.

Any updates? :)
